
version: "3"

services:
  kafka0:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka0
    hostname: kafka0
    restart: unless-stopped
    ports:
      # - "9094:9094"
      - "9094:9092"
    # networks:
    #   big-data-net-kafka:
    #     ipv4_address: 10.1.0.3
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - ./kafka0_data:/bitnami/kafka
    env_file:
      - stack.env
  kafka1:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka1
    hostname: kafka_
    restart: unless-stopped
    ports:
      # - "9095:9094"
      - "9095:9092"
    # networks:
    #   big-data-net-kafka:
    #     ipv4_address: 10.1.0.4
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - ./kafka1_data:/bitnami/kafka
    env_file:
      - stack.env

volumes:
  kafka0_data:
    driver: local
  kafka1_data:
    driver: local
# networks:
#   big-data-net-kafka:
#     name: big-data-net-kafka
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.1.0.0/16
