version: '3.5'

services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports: #If you use it as localhost, then it maps the right port to the left one. If you use it from the outside, the port on the right side stays, and you should use the ipv4 address provided below.
      - "9090:8080"
      - "7077:7077"
    expose:
      - "9090:8080"
      - "7077:7077"
    networks:
      big-data-net:
        ipv4_address: 10.0.0.20
    cap_add: #Enabling the container to manage the networking.
      - NET_ADMIN
      
  spark-worker-1:
    container_name: spark-worker-1
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      big-data-net:
        ipv4_address: 10.0.0.21
    cap_add:
      - NET_ADMIN
      
  spark-worker-2:
    container_name: spark-worker-2
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      big-data-net:
        ipv4_address: 10.0.0.22
    cap_add:
      - NET_ADMIN
      
 
  jupyter:
    container_name: jupyter
    image: "jupyter/all-spark-notebook"
    volumes: #Maps the jupyter container folder on the right to local folder on the left.
      - ${path}/jupyter:/home/jovyan/work
    ports:
      - 8888:8888
    networks:
      big-data-net:
        ipv4_address: 10.0.0.23
    cap_add:
      - NET_ADMIN
    env_file:
      - stack.env
    environment: # enables a sudo privilages in the container
      - GRANT_SUDO=yes
    command: /bin/sh -c  "start-notebook.sh --user root --NotebookApp.token=''" # enables a sudo privilages in the container

networks:
  big-data-net:
    name: big-data-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
    external: true

