version: '3.7'

services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 9090:8080
      - 7077:7077
    networks:
      big-data-net-spark:
        ipv4_address: 10.3.0.2
    cap_add:
      - NET_ADMIN
      
  spark-worker-1:
    container_name: spark-worker-1
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      big-data-net-spark:
        ipv4_address: 10.3.0.3
    cap_add:
      - NET_ADMIN
      
  spark-worker-2:
    container_name: spark-worker-2
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      big-data-net-spark:
        ipv4_address: 10.3.0.4
    cap_add:
      - NET_ADMIN
      
  tailscale_spark:
    image: tailscale/tailscale:stable
    container_name: tailscale_spark
    hostname: tailscale
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      big-data-net-spark:
        ipv4_address: 10.3.0.5
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${path}/tailscale:/var/lib
    env_file:
      - stack.env
    environment:
      - TS_ROUTES=10.3.0.0/16
      - TS_HOSTNAME=spark
 
  pyspark:
    container_name: pyspark
    image: "jupyter/all-spark-notebook"
    volumes:
      - ${path}/jupyter:/home/jovyan/work
    ports:
      - 8888:8888
    networks:
      big-data-net-spark:
        ipv4_address: 10.3.0.6
    cap_add:
      - NET_ADMIN
    env_file:
      - stack.env
    environment:
      - GRANT_SUDO=yes
    command: /bin/sh -c  "start-notebook.sh --user root --NotebookApp.token=''"

networks:
  big-data-net-spark:
    name: big-data-net-spark
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16

