# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "3"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    hostname: kafka
    restart: unless-stopped
    ports:
      - '9092:9092'
    volumes:
      - "./kafka_data:/bitnami"
    env_file:
      - stack.env
volumes:
  kafka_data:
    driver: local
