version: '3'
services:
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    volumes:
      - ./hive_server:/hive_server
    env_file:
      - ./stack.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "10.0.0.31:9083"
    networks:
      big-data-net:
        ipv4_address: 10.0.0.30
    ports:
      - 10000:10000
    cap_add:
      - NET_ADMIN

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./stack.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "10.0.0.2:9870 10.0.0.3:9864 10.0.0.32:5432"
    networks:
      big-data-net:
        ipv4_address: 10.0.0.31
    ports:
      - 9083:9083
    cap_add:
      - NET_ADMIN

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    volumes:
      - ./metastore-postgresql/postgresql/data:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    networks:
      big-data-net:
        ipv4_address: 10.0.0.32
    ports:
      - 5432:5432
    cap_add:
      - NET_ADMIN
  
  #presto-coordinator:
  #  container_name: presto-coordinator
  #  image: shawnzhu/prestodb:0.181
  #  networks:
  #    big-data-net:
  #      ipv4_address: 10.0.0.33
  #  ports:
  #    - "8050:8080"
  #  cap_add:
  #    - NET_ADMIN

  #hbase:
  #  image: coomia/hbase2.2:0.1
  #  container_name: hbase
  #  volumes:
  #    - hbase_data:/hbase_data
  #    - hbase_zookeeper_data:/zookeeper_data
  #  ports:
  #    - 16000:16000
  #    - 16010:16010
  #    - 16020:16020
  #    - 16030:16030
  #    - 2888:2888
  #    - 3888:3888
  #    - 2181:2181
  #    - 9091:9090
  #  environment:
  #    SERVICE_PRECONDITION: "10.0.0.2:9870 10.0.0.3:9864"
  #  networks:
  #    big-data-net:
  #      ipv4_address: 10.0.0.33
  #  env_file:
  #    - ./stack.env
  #  cap_add:
  #    - NET_ADMIN
  
    
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000 # http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${path}/portainer_data:/data
    restart: unless-stopped
    networks:
      big-data-net:
        ipv4_address: 10.0.0.34
    env_file:
      - ./stack.env

volumes:
  pgdata:
  #./metastore-postgresql/postgresql/data:
  
networks:
  big-data-net:
    name: big-data-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
    external: true