version: '3'
services:
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    volumes:
      - ./hive_server:/hive_server
    env_file:
      - ./stack.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    networks:
      big-data-net-hive-hbase:
        ipv4_address: 10.4.0.2
    ports:
      - 10000:10000
    cap_add:
      - NET_ADMIN

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./stack.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "10.0.0.2:9870 10.0.0.3:9864 hive-metastore-postgresql:5432"
    networks:
      big-data-net-hive-hbase:
        ipv4_address: 10.4.0.3
    ports:
      - 9083:9083
    cap_add:
      - NET_ADMIN

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    volumes:
      - ./metastore-postgresql/postgresql/data:/var/lib/postgresql/data
    networks:
      big-data-net-hive-hbase:
        ipv4_address: 10.4.0.4
    cap_add:
      - NET_ADMIN

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    volumes:
      - hbase_data:/hbase_data
      - hbase_zookeeper_data:/zookeeper_data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "10.0.0.2:9870 10.0.0.3:9864"
    networks:
      big-data-net-hive-hbase:
        ipv4_address: 10.4.0.5
    env_file:
      - ./stack.env
    cap_add:
      - NET_ADMIN

  tailscale_hive-hbase:
    image: tailscale/tailscale:stable
    container_name: tailscale_hive-hbase
    hostname: tailscale
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      big-data-net-hive-hbase:
        ipv4_address: 10.4.0.6
    env_file:
      - stack.env
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${path}/tailscale:/var/lib
    environment:
      - TS_ROUTES=10.4.0.0/16
      - TS_HOSTNAME=hive-hbase

volumes:
  hbase_data:
  hbase_zookeeper_data:

networks:
  big-data-net-hive-hbase:
    name: big-data-net-hive-hbase
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16